Repository exorteam/Exort, pull requests merged in 2019-07, with the labels that each got.

#4 first iteration
  doc/第一次迭代计划.md
Labels: document

#5 doc for mysql remote deploy
  doc/关于在远程服务器上部署mysql的尝试.md
Labels: document

#6 接口描述文档
  README.md
  doc/interface.md
Labels: document

#7 front-end frame
  FrontEnd/npm
  FrontEnd/package-lock.json
  FrontEnd/package.json
  FrontEnd/src/App.vue
  FrontEnd/src/components/index.vue
  FrontEnd/src/main.js
  FrontEnd/src/router/index.js
Labels: enhancement

#8 association member management
  FrontEnd/src/components/association_member_management/application_management_table.vue
  FrontEnd/src/components/association_member_management/member_management._table.vue
  FrontEnd/src/router/index.js
Labels: enhancement

#19 K8sdeploy
  doc/about_deploy_k8s.md
Labels: document

#25 doc
  FrontEnd/src/router/index.js
  association_member_management/pom.xml
  association_member_management/src/main/java/com/exort/association_member_management/controller/AssociationMemberManageController.java
  association_member_management/src/main/java/com/exort/association_member_management/entity/Application.java
  association_member_management/src/main/java/com/exort/association_member_management/repository/ApplicationRepository.java
  association_member_management/src/main/java/com/exort/association_member_management/service/ApplicationService.java
  association_member_management/src/main/java/com/exort/association_member_management/serviceimpl/ApplicationServiceImpl.java
  association_member_management/src/main/resources/application.properties
  association_member_management/src/main/resources/application.yml
  doc/第一周工作总结/img/git_workflow.png
  doc/第一周工作总结/img/sprint_board1.png
  doc/第一周工作总结/img/sprint_board2.png
  doc/第一周工作总结/小组工作总结.md
  doc/第一周工作总结/工作总结_张万强.md
  doc/第一周工作总结/工作总结_芮召普.md
  doc/第一周工作总结/工作总结_邓公淯.md
  doc/第一周工作总结/工作总结_陈景宇.md
  doc/第一次迭代计划.md
Labels: document

#30 finished k8s deployment
  doc/about_deploy_k8s.md
  doc/images/k8s_screenshot.png
  doc/第一周工作总结/小组工作总结.md
  doc/第一周工作总结/工作总结_邓公淯.md
  script/append_host.sh
  script/prepare_master.sh
  script/prepare_node.sh
  script/scp_scripts.sh
Labels: document

#39 添加架构设计说明
  doc/architecture.md
  doc/images/architecture.png
  doc/images/mysql.png
Labels: document

#57 successfully deployed mysql
  operation/deploy/mysql/mysql-core.yaml
  operation/deploy/mysql/mysql-pv.yaml
  operation/deploy/mysql/mysql-pvc.yaml
  operation/deploy/mysql/mysql-secret.yaml
  operation/deploy/mysql/mysql-service.yaml
Labels: work

#60 Association member manager
  association_member_manager/doc/interface.md
Labels: document

#67 Successfully deployed database
  operation/deploy/mongo/.gitignore
  operation/deploy/mongo/README.md
  operation/deploy/mongo/mongo-deploy.yaml
  operation/deploy/mongo/mongo-secret.yaml
  operation/deploy/mysql/README.md
  operation/deploy/mysql/mysql-core.yaml
  operation/deploy/mysql/mysql-deploy.yaml
  operation/deploy/mysql/mysql-pv.yaml
  operation/deploy/mysql/mysql-pvc.yaml
  operation/deploy/mysql/mysql-service.yaml
  operation/deploy/storageClass-manual.yaml
Labels: work

#70 Asso manager interface
  association_manager/doc/association_manager_interface.md
Labels: document

#73 To deploy k8s
  operation/doc/install_helm_tiller_istio.md
  operation/script/prepare_master.sh
  operation/script/prepare_node.sh
Labels: work

#72 Apply review
  review_manager/doc/interface.md
  review_manager/doc/spec_http.md
Labels: document

#76 deploy istio
  operation/doc/images/k8s_screenshot.png
  operation/doc/install_helm_tiller_istio.md
  operation/doc/install_istio.md
  operation/doc/install_k8s.md
Labels: document

#78 Activity management interface
  activity_manager/doc/activity_management_interface.md
  activity_manager/doc/activity_management_spec_http.md
Labels: document

#79 update spec_http.md
  activity_manager/doc/activity_management_spec_http.md
Labels: document

#82 Apply review
  review_manager/doc/spec_http.md
Labels: document

#83 Association mem manager back
  association_member_manager/doc/interface.md
  association_member_manager/doc/spec_http.md
  association_member_manager/pom.xml
  association_member_manager/src/main/java/com/exort/association_member_management/config/SwaggerConfig.java
  association_member_manager/src/main/java/com/exort/association_member_management/controller/AssociationMemberManageController.java
  association_member_manager/src/main/java/com/exort/association_member_management/dto/ResponseCode.java
  association_member_manager/src/main/java/com/exort/association_member_management/entity/Application.java
  association_member_manager/src/main/java/com/exort/association_member_management/entity/Department.java
  association_member_manager/src/main/java/com/exort/association_member_management/entity/DepartmentId.java
  association_member_manager/src/main/java/com/exort/association_member_management/repository/ApplicationRepository.java
  association_member_manager/src/main/java/com/exort/association_member_management/repository/DepartmentRepository.java
  association_member_manager/src/main/java/com/exort/association_member_management/service/ApplicationService.java
  association_member_manager/src/main/java/com/exort/association_member_management/service/AssociationMemberManageService.java
  association_member_manager/src/main/java/com/exort/association_member_management/serviceimpl/ApplicationServiceImpl.java
  association_member_manager/src/main/java/com/exort/association_member_management/serviceimpl/AssociationMemberManageServiceImpl.java
  association_member_manager/src/main/resources/application.yml
  web_client/src/components/activity/Activity.vue
  web_client/src/components/association_member_management/member_management._table.vue
  web_client/src/components/index.vue
Labels: document, enhancement

#87 Auth
  authentication/doc/interface.md
  authentication/doc/spec_http.md
Labels: document

#89 第一次迭代doc
  doc/第一次迭代/测试报告.docx
  doc/第一次迭代/测试用例.xls
  doc/第一次迭代/第一次迭代计划.md
  doc/第一次迭代/第一次迭代评估报告.md
Labels: document

#91 Create 工作总结_陈景宇.md
  doc/第二周工作总结/工作总结_陈景宇.md
Labels: document

#86 Asso manager spec http
  association_manager/doc/association_manager_interface.md
  association_manager/doc/association_manager_spec_http.md
Labels: document

#95 后台界面设计
  web_client/doc/后台界面设计/images/Platform.png
  web_client/doc/后台界面设计/images/side.png
  web_client/doc/后台界面设计/后台界面设计.md
Labels: document

#96 Api server
  .drone.yml
  api_server/.gitignore
  api_server/Dockerfile
  api_server/apiserver.yaml
  api_server/pom.xml
  api_server/src/main/java/exort/apiserver/ApiserverApplication.java
  api_server/src/main/java/exort/apiserver/component/SecurityUtil.java
  api_server/src/main/java/exort/apiserver/config/CrossOriginConfig.java
  api_server/src/main/java/exort/apiserver/config/SecurityConfig.java
  api_server/src/main/java/exort/apiserver/controller/LoginController.java
  api_server/src/main/java/exort/apiserver/controller/UserServiceController.java
  api_server/src/main/java/exort/apiserver/entity/UserInfo.java
  api_server/src/main/java/exort/apiserver/repository/UserRepository.java
  api_server/src/main/java/exort/apiserver/service/UserService.java
  api_server/src/main/java/exort/apiserver/serviceimpl/MyUserDetailsServiceImpl.java
  api_server/src/main/java/exort/apiserver/serviceimpl/UserServiceImpl.java
  api_server/src/main/resources/application.properties
  doc/第二周工作总结/第二周工作总结_邓公淯.md
Labels: document, enhancement, work

#101 web client modify
  web_client/src/App.vue
  web_client/src/components/admin_index.vue
  web_client/src/components/association_member_management/association_member_table.vue
  web_client/src/router/index.js
Labels: bug, enhancement

#102 完成标签管理模块的接口设计, 待添加 example
  tag_manager/doc/interface.md
  tag_manager/doc/spec_http.md
Labels: document

#99 Association manager backend
  article_manager/src/main/java/exort/articlemanager/controller/ArticleController.java
  association_manager/.gitignore
  association_manager/doc/association_manager_spec_http.md
  association_manager/java_test.java
  association_manager/pom.xml
  association_manager/src/main/java/exort/associationmanager/AssociationManagerApplication.java
  association_manager/src/main/java/exort/associationmanager/controller/ArticleController.java
  association_manager/src/main/java/exort/associationmanager/controller/AssociationManagementController.java
  association_manager/src/main/java/exort/associationmanager/controller/AssociationManagerController.java
  association_manager/src/main/java/exort/associationmanager/entity/Application.java
  association_manager/src/main/java/exort/associationmanager/entity/Article.java
  association_manager/src/main/java/exort/associationmanager/entity/ArticleFilterParams.java
  association_manager/src/main/java/exort/associationmanager/entity/Association.java
  association_manager/src/main/java/exort/associationmanager/entity/AssociationApplication.java
  association_manager/src/main/java/exort/associationmanager/entity/AssociationFilterParams.java
  association_manager/src/main/java/exort/associationmanager/entity/AssociationInfo.java
  association_manager/src/main/java/exort/associationmanager/entity/AssociationList.java
  association_manager/src/main/java/exort/associationmanager/entity/MyObject.java
  association_manager/src/main/java/exort/associationmanager/entity/ResponseBody.java
  association_manager/src/main/java/exort/associationmanager/repository/ArticleRepository.java
  association_manager/src/main/java/exort/associationmanager/repository/AssociationRepository.java
  association_manager/src/main/java/exort/associationmanager/service/ArticleService.java
  association_manager/src/main/java/exort/associationmanager/service/AssociationService.java
  association_manager/src/main/java/exort/associationmanager/serviceimpl/ArticleServiceImpl.java
  association_manager/src/main/java/exort/associationmanager/serviceimpl/AssociationServiceImpl.java
  association_manager/src/main/resources/application.properties
  association_manager/src/test/java/exort/associationmanager/AssociationManagerApplicationTests.java
  association_manager/src/test/java/exort/associationmanager/service/AssociationServiceTest.java
Labels: enhancement

#100 Permission management design
  permission_manager/doc/interface.md
  permission_manager/doc/spec_http.md
Labels: document

#104 Iteration2
  doc/第二次迭代/第二次迭代.md
Labels: document

#105 update activity
  User_manager/doc/user_manager_interface.md
  User_manager/doc/user_manager_spec_http.md
  activity_manager/doc/activity_management_interface.md
  activity_manager/doc/activity_management_spec_http.md
  activity_manager/pom.xml
  activity_manager/src/main/java/exort/activity/ActivityApplication.java
  activity_manager/src/main/java/exort/activity/controller/ActivityController.java
  activity_manager/src/main/java/exort/activity/controller/ActivitySignUpController.java
  activity_manager/src/main/java/exort/activity/dao/ActivityDao.java
  activity_manager/src/main/java/exort/activity/dao/ActivitySignUpDao.java
  activity_manager/src/main/java/exort/activity/daoImpl/ActivityDaoImpl.java
  activity_manager/src/main/java/exort/activity/daoImpl/ActivitySignUpDaoImpl.java
  activity_manager/src/main/java/exort/activity/entity/Activity.java
  activity_manager/src/main/java/exort/activity/entity/ActivitySignUp.java
  activity_manager/src/main/java/exort/activity/entity/ActivityTime.java
  activity_manager/src/main/java/exort/activity/entity/Operation.java
  activity_manager/src/main/java/exort/activity/entity/PageList.java
  activity_manager/src/main/java/exort/activity/entity/Response.java
  activity_manager/src/main/java/exort/activity/entity/Select.java
  activity_manager/src/main/java/exort/activity/entity/TimeRange.java
  activity_manager/src/main/java/exort/activity/repository/ActivityRepository.java
  activity_manager/src/main/java/exort/activity/repository/ActivitySignUpRepository.java
  activity_manager/src/main/java/exort/activity/service/ActivityService.java
  activity_manager/src/main/java/exort/activity/service/ActivitySignUpService.java
  activity_manager/src/main/java/exort/activity/serviceImpl/ActivityServiceImpl.java
  activity_manager/src/main/java/exort/activity/serviceImpl/ActivitySignUpServiceImpl.java
  activity_manager/src/main/resources/application.properties
Labels: document

#107 modify doc
  association_member_manager/doc/interface.md
  association_member_manager/doc/spec_http.md
Labels: document

#114 Activity dev
  web_client/src/components/activity/activity.vue
  web_client/src/components/activity/activity_create.vue
  web_client/src/components/activity/build.vue
  web_client/src/components/activity/tag_choose.vue
  web_client/src/components/admin_index.vue
  web_client/src/router/index.js
Labels: document

#125 weekly doc
  doc/第三周工作总结/images/1.png
  doc/第三周工作总结/小组工作总结.md
  doc/第三周工作总结/工作总结_张万强.md
Labels: document

#128 refactor
  .drone.yml
  common/pom.xml
  common/src/main/java/exort/api/http/entity/ApiResponse.java
  common/src/main/java/exort/api/http/member/entity/Department.java
  common/src/main/java/exort/api/http/review/entity/Application.java
  common/src/main/java/exort/api/http/review/entity/ApplicationDepartmentInfo.java
  common/src/test/java/exort/api/http/review/entity/ApplicationTest.java
Labels: enhancement

#135 加入了association manager的service
  common/src/main/java/exort/api/http/assomgr/entity/ApplicationAssociationInfo.java
  common/src/main/java/exort/api/http/assomgr/entity/Association.java
  common/src/main/java/exort/api/http/assomgr/entity/AssociationFilterParams.java
  common/src/main/java/exort/api/http/assomgr/entity/AssociationInfo.java
  common/src/main/java/exort/api/http/assomgr/entity/AssociationList.java
  common/src/main/java/exort/api/http/assomgr/entity/PatchAssociationInfo.java
  common/src/main/java/exort/api/http/assomgr/service/AssociationManagerService.java
  common/src/main/java/exort/api/http/assomgr/service/AssociationServiceImpl.java
Labels: enhancement

#137 Common association manager
  common/src/main/java/exort/api/http/assomgr/entity/ApplicationAssociationInfo.java
  common/src/main/java/exort/api/http/assomgr/entity/AssociationInfo.java
  common/src/main/java/exort/api/http/assomgr/entity/AssociationList.java
  common/src/main/java/exort/api/http/assomgr/entity/PatchAssociationInfo.java
  common/src/main/java/exort/api/http/assomgr/service/AssociationManagerService.java
  common/src/main/java/exort/api/http/assomgr/service/AssociationServiceImpl.java
Labels: enhancement

#143 添加了新的接口和测试
  .drone.yml
  permission_manager/pom.xml
  permission_manager/src/main/java/exort/permission_manager/controller/PermController.java
  permission_manager/src/main/java/exort/permission_manager/controller/RoleController.java
  permission_manager/src/main/java/exort/permission_manager/controller/UserController.java
  permission_manager/src/main/java/exort/permission_manager/entity/ExortRole.java
  permission_manager/src/main/java/exort/permission_manager/repository/PermRepository.java
  permission_manager/src/main/java/exort/permission_manager/repository/RoleRepository.java
  permission_manager/src/main/java/exort/permission_manager/repository/UserScopeRoleRepository.java
  permission_manager/src/main/java/exort/permission_manager/service/PermService.java
  permission_manager/src/main/java/exort/permission_manager/service/RoleService.java
  permission_manager/src/main/java/exort/permission_manager/service/UserService.java
  permission_manager/src/main/java/exort/permission_manager/serviceimpl/PermServiceImpl.java
  permission_manager/src/main/java/exort/permission_manager/serviceimpl/RoleServiceImpl.java
  permission_manager/src/main/java/exort/permission_manager/serviceimpl/UserServiceImpl.java
  permission_manager/src/test/java/exort/permission_manager/repository/RolePermRepositoryTest.java
  permission_manager/src/test/java/exort/permission_manager/repository/UserScopeRoleRepositoryTest.java
  permission_manager/src/test/java/exort/permission_manager/serviceimpl/PermServiceImplTest.java
  permission_manager/src/test/java/exort/permission_manager/serviceimpl/RoleServiceImplTest.java
  permission_manager/src/test/java/exort/permission_manager/serviceimpl/UserServiceImplTest.java
Labels: enhancement

#146 add constructor for some activity entity class, and modify some code …
  common/pom.xml
  common/src/main/java/exort/api/http/activity/entity/Activity.java
  common/src/main/java/exort/api/http/activity/entity/ActivityTime.java
  common/src/main/java/exort/api/http/activity/entity/Signup.java
  common/src/main/java/exort/api/http/activity/entity/TimeRange.java
  common/src/main/java/exort/api/http/activity/service/ActivityService.java
  common/src/main/java/exort/api/http/activity/service/ActivityServiceImpl.java
Labels: enhancement

#148 Perm mgr
  .drone.yml
  permission_manager/.gitignore
  permission_manager/doc/spec_http.md
  permission_manager/pom.xml
  permission_manager/src/main/java/exort/permission_manager/PermissionManagerApplication.java
  permission_manager/src/main/java/exort/permission_manager/controller/PermController.java
  permission_manager/src/main/java/exort/permission_manager/controller/RoleController.java
  permission_manager/src/main/java/exort/permission_manager/controller/UserController.java
  permission_manager/src/main/java/exort/permission_manager/entity/ExortPerm.java
  permission_manager/src/main/java/exort/permission_manager/entity/ExortRole.java
  permission_manager/src/main/java/exort/permission_manager/entity/RolePerm.java
  permission_manager/src/main/java/exort/permission_manager/entity/UserScopeRole.java
  permission_manager/src/main/java/exort/permission_manager/repository/PermRepository.java
  permission_manager/src/main/java/exort/permission_manager/repository/RolePermRepository.java
  permission_manager/src/main/java/exort/permission_manager/repository/RoleRepository.java
  permission_manager/src/main/java/exort/permission_manager/repository/UserScopeRoleRepository.java
  permission_manager/src/main/java/exort/permission_manager/service/PermService.java
  permission_manager/src/main/java/exort/permission_manager/service/RoleService.java
  permission_manager/src/main/java/exort/permission_manager/service/UserService.java
  permission_manager/src/main/java/exort/permission_manager/serviceimpl/PermServiceImpl.java
  permission_manager/src/main/java/exort/permission_manager/serviceimpl/RoleServiceImpl.java
  permission_manager/src/main/java/exort/permission_manager/serviceimpl/UserServiceImpl.java
  permission_manager/src/test/java/exort/permission_manager/repository/RolePermRepositoryTest.java
  permission_manager/src/test/java/exort/permission_manager/repository/UserScopeRoleRepositoryTest.java
  permission_manager/src/test/java/exort/permission_manager/serviceimpl/PermServiceImplTest.java
  permission_manager/src/test/java/exort/permission_manager/serviceimpl/RoleServiceImplTest.java
  permission_manager/src/test/java/exort/permission_manager/serviceimpl/UserServiceImplTest.java
Labels: document, enhancement

#149 删除checkperm，添加scope和roleName两个接口
  common/src/main/java/exort/api/http/member/service/AssoMemService.java
  common/src/main/java/exort/api/http/member/service/AssoMemServiceImpl.java
Labels: work

#144 Asso mem manage
  .drone.yml
  association_member_manager/.gitignore
  association_member_manager/doc/spec_http.md
  association_member_manager/pom.xml
  association_member_manager/src/main/java/com/exort/association_member_management/controller/AssociationMemberManageController.java
  association_member_manager/src/main/java/com/exort/association_member_management/dto/ResponseCode.java
  association_member_manager/src/main/java/com/exort/association_member_management/entity/Application.java
  association_member_manager/src/main/java/com/exort/association_member_management/repository/ApplicationRepository.java
  association_member_manager/src/main/java/com/exort/association_member_management/repository/DepartmentRepository.java
  association_member_manager/src/main/java/com/exort/association_member_management/service/AssociationMemberManageService.java
  association_member_manager/src/main/java/com/exort/association_member_management/serviceimpl/AssociationMemberManageServiceImpl.java
  association_member_manager/src/main/java/exort/association_member_manager/AssociationMemberManagementApplication.java
  association_member_manager/src/main/java/exort/association_member_manager/config/SwaggerConfig.java
  association_member_manager/src/main/java/exort/association_member_manager/controller/AssociationMemberManageController.java
  association_member_manager/src/main/java/exort/association_member_manager/entity/Department.java
  association_member_manager/src/main/java/exort/association_member_manager/entity/DepartmentId.java
  association_member_manager/src/main/java/exort/association_member_manager/repository/DepartmentRepository.java
  association_member_manager/src/main/java/exort/association_member_manager/service/AssociationMemberManageService.java
  association_member_manager/src/main/java/exort/association_member_manager/serviceimpl/AssociationMemberManageServiceImpl.java
  association_member_manager/src/main/resources/application.yml
  association_member_manager/src/test/java/exort/association_member_manager/AssociationMemberManagementApplicationTests.java
  association_member_manager/src/test/java/exort/association_member_manager/serviceimpl/AssociationMemberManageServiceImplTest.java
  web_client/src/components/activity/about.vue
  web_client/src/components/activity/activity.vue
  web_client/src/components/admin_index.vue
  web_client/src/components/admin_nav/nav.vue
  web_client/src/components/admin_nav/notice.vue
  web_client/src/components/admin_nav/user.vue
  web_client/src/components/association_member_management/application_management_table.vue
  web_client/src/components/association_member_management/association_member_table.vue
  web_client/src/components/auth/signin/signin_table.vue
  web_client/src/components/sidebar/assoSidebar.vue
  web_client/src/components/sidebar/sysSidebar.vue
  web_client/src/router/index.js
  web_client/src/store/index.js
Labels: work

#154 update code
  api_server/src/main/java/exort/apiserver/controller/ActivityManagerController.java
  api_server/src/main/java/exort/apiserver/controller/AssociationManagerController.java
Labels: enhancement

#155 update for association id type
  common/src/main/java/exort/api/http/activity/entity/Activity.java
  common/src/main/java/exort/api/http/activity/entity/Filter.java
  common/src/main/java/exort/api/http/activity/entity/Signup.java
Labels: enhancement

#157 push
  web_client/src/components/activity/build.vue
  web_client/src/components/assoadmin/activity/about.vue
  web_client/src/components/assoadmin/activity/activity.vue
  web_client/src/components/assoadmin/activity/activity_create.vue
  web_client/src/components/assoadmin/activity/expand_table.vue
  web_client/src/components/assoadmin/activity/tag_choose.vue
  web_client/src/components/assoadmin/activity/time_range.vue
  web_client/src/router/index.js
Labels: enhancement

#160 Mem api server
  api_server/src/main/java/exort/apiserver/controller/AssoMemManagerController.java
Labels: work

#151 社团管理模块（final）
  .drone.yml
  api_server/src/main/java/exort/apiserver/service/impl/AssociationManagerImpl.java
  association_manager/.gitignore
  association_manager/doc/association_manager_frontend_requirement.md
  association_manager/doc/association_manager_interface.md
  association_manager/doc/association_manager_spec_http.md
  association_manager/java_test.java
  association_manager/pom.xml
  association_manager/src/main/java/exort/associationmanager/AssociationManagerApplication.java
  association_manager/src/main/java/exort/associationmanager/config/CorsConfig.java
  association_manager/src/main/java/exort/associationmanager/controller/AssociationManagerController.java
  association_manager/src/main/java/exort/associationmanager/entity/Application.java
  association_manager/src/main/java/exort/associationmanager/entity/Association.java
  association_manager/src/main/java/exort/associationmanager/entity/AssociationFilterParams.java
  association_manager/src/main/java/exort/associationmanager/entity/AssociationInfo.java
  association_manager/src/main/java/exort/associationmanager/entity/AssociationList.java
  association_manager/src/main/java/exort/associationmanager/entity/MyObject.java
  association_manager/src/main/java/exort/associationmanager/entity/ResponseBody.java
  association_manager/src/main/java/exort/associationmanager/repository/AssociationRepository.java
  association_manager/src/main/java/exort/associationmanager/service/AssociationService.java
  association_manager/src/main/java/exort/associationmanager/serviceimpl/AssociationServiceImpl.java
  association_manager/src/test/java/exort/associationmanager/AssociationManagerApplicationTests.java
  association_manager/src/test/java/exort/associationmanager/service/AssociationServiceTest.java
  association_manager/src/test/java/exort/associationmanager/serviceImpl/AssociationServiceImplTest.java
  auth/pom.xml
  doc/interface.md
Labels: enhancement

#163 Mem front
  web_client/src/components/assoadmin/association_member_management/application_management_table.vue
  web_client/src/components/assoadmin/association_member_management/asso_mem_perm.vue
  web_client/src/components/assoadmin/association_member_management/association_member_table.vue
  web_client/src/router/index.js
Labels: work

#164 重构了api-server的association部分的代码
  api_server/src/main/java/exort/apiserver/ApiserverApplication.java
  api_server/src/main/java/exort/apiserver/controller/AssociationManagerController.java
  api_server/src/main/java/exort/apiserver/service/AssociationManagerService.java
  api_server/src/main/java/exort/apiserver/service/impl/AssociationServiceImpl.java
Labels: enhancement
